name: Python Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          # Instala Chrome oficial
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          # Instala ChromeDriver compatible
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}')
          CHROME_MAJOR_VERSION=${CHROME_VERSION%%.*}
          wget -q https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION} -O /tmp/chromedriver-version
          CHROMEDRIVER_VERSION=$(cat /tmp/chromedriver-version)
          wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip -O /tmp/chromedriver.zip
          sudo unzip -o /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          # Verifica instalación
          google-chrome-stable --version
          chromedriver --version

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export PATH=$PATH:/usr/local/bin  # Asegura acceso a chromedriver
          behave -f behave_html_formatter:HTMLFormatter -o test-report.html
        env:
          PYTHONUNBUFFERED: "1"

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: behave-report
          path: test-report.html
