name: Python Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Verify Chrome & ChromeDriver (Preinstalados)
        run: |
          google-chrome --version  # Verifica Chrome
          chromedriver --version   # Verifica ChromeDriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt behave-html-formatter --no-cache-dir

      - name: Run tests with Behave
        run: |
          mkdir -p reports  # Crea directorio para reportes
          behave -f behave_html_formatter:HTMLFormatter -o reports/test-report.html
        env:
          HEADLESS: "true"
          PYTHONUNBUFFERED: "1"

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: behave-test-report
          path: reports/test-report.html # Ruta del reporte HTML
